### PR TITLE
Add option :repo_module to opts.

### PR DESCRIPTION
**Pull request by scouten**

### CODE REVIEW

**Comment by scouten** [comment]
@DavidAntaramian: I had trouble running tests locally, so this is a blind patch to meet some of my needs. Any advice?

```
$ mix test

10:28:10.015 [error] GenServer #PID<0.164.0> terminating
** (KeyError) key :database not found in: [pool: DBConnection.Poolboy, types: true, hostname: "localhost", username: "scouten", types: true, otp_app: :tributary, repo: Tributary.Repo, adapter: Ecto.Adapters.Postgres, pool_timeout: 5000, timeout: 15000, adapter: Ecto.Adapters.Postgres, extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432]
    (elixir) lib/keyword.ex:333: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:77: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

```
$ mix ecto.create
warning: could not find repositories for application :tributary.

You can avoid this warning by passing the -r flag or by setting the
repositories managed by this application in your config/config.exs:

    config :tributary, ecto_repos: [...]

The configuration may be an empty list if it does not define any repo.
```

**Comment by DavidAntaramian** [comment]
Ah, that's a bad documentation issue. I can get to that this evening after work.

**Comment by DavidAntaramian** [comment]
@scouten See if these instructions help: https://github.com/DavidAntaramian/tributary#testing

**Comment by scouten** [comment]
Yes, I think that works. I'll close this. Thanks.

**Pull request closed without merging**
